[project]
name = "moderner-cv"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
watch = "typst watch --font-path=fonts example.typ"
compile = "typst compile --font-path=fonts example.typ"

[dependencies]
typst = ">=0.11.1,<0.12"
typstyle = ">=0.11.28,<0.12"
